### ISSUE TITLE
failed: Close received after close

### ISSUE THREAD

**Issue by chjiyun** [coder/websocket#448]
Hello, I recently encountered a problem. Can someone help me take a look？，
I used the [example](https://github.com/nhooyr/websocket/tree/master/internal/examples/chat) and successfully ran it, but I sent a ping to the server and received an error below:
```
WebSocket connection to 'ws://127.0.0.1:8888/subscribe' failed: Close received after close
```

**Comment by nhooyr** [comment]
Can you show your client code?

**Comment by chjiyun** [comment]
@nhooyr  go version 1.22.2
```
conn.addEventListener('open', ev => {
    console.info('websocket connected')
    setTimeout(() => {
      conn.send('ping')
    }, 3000)
  })
```

**Comment by nhooyr** [comment]
Unrelated to the library. Something's wrong with your client code calling close after the connection has been closed. See https://github.com/mqttjs/MQTT.js/issues/1361

**Comment by fogrye** [comment]
I would reopen this as after last update as have received same error with native WebSocket in Chrome, while safari is ok with that.

**Comment by nhooyr** [comment]
Ok possible we need to add a guard in `c.writeClose` to not write a close frame twice. I think that we're writing a close frame, we get a close frame back and then the code doesn't keep track that it already wrote a close frame and so writes a close frame in response to the handshake close frame.

**Comment by fogrye** [comment]
Yes, I saw that it's waiting for closing but CloseNow did not check if it was closed already. I believe that's what's happening.

**Comment by dgpc** [comment]
Is https://github.com/coder/websocket/pull/476 the chosen approach here, and if so anything we can do to get it merged? My application is experiencing this same issue.

I also noticed another project had decided to fork the library in order to pick up this solution: https://github.com/flowey-org/websocket/commit/b1784e66892beb81fbfa91d896d35bc605f6b5f6.

**Comment by rslobodian** [comment]
Hi, I'm a user of this library and thank you for fixing this issue. Question: is there an ETA for this fix to be released? It seems like the last public release was v1.8.12 from Aug 9, 2024. 
Thanks!

**Comment by mafredri** [comment]
@rslobodian happy to hear this fixed your issue! We're aiming to do a release next week 🤞🏻.
