### ISSUE TITLE
JSON parser

### ISSUE THREAD

**Issue by kehiy** [coder/websocket#479]
At the moment the `wsjson` utilizes `encoding/json` which is very slow compared to other parsers such as `mailru/easyjson` or `jsoniter`. I think we can use one of the existing fast packages or implement the parser on `wsjson` ourselves which makes everything faster.

If you thing this `wsjson` it something that we can change, let me know so I can make a PR and update this.

**Comment by ash2k** [comment]
Please, don't add any new dependencies to the library - most people don't use the `wsjson` package, yet will get extra dependencies. It's under 100 lines of code - anyone who cares about performance may copy it and use their favorite json library.

**Comment by kehiy** [comment]
@ash2k thanks.
